# Generated by Django 2.2.3 on 2021-08-26 01:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('programming', '0012_auto_20200608_1252'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionTypeBlockly',
            fields=[
                ('question_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='programming.Question')),
            ],
            options={
                'verbose_name': 'Blockly Question',
                'verbose_name_plural': 'Blockly Questions',
            },
            bases=('programming.question',),
        ),
        migrations.CreateModel(
            name='QuestionTypeBlocklyTestCase',
            fields=[
                ('testcase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='programming.TestCase')),
                ('test_input', models.CharField(blank=True, max_length=500)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_cases', to='programming.QuestionTypeBlockly')),
            ],
            options={
                'verbose_name': 'Blockly Question Test Case',
            },
            bases=('programming.testcase',),
        ),
    ]
