# Generated by Django 3.2.6 on 2021-10-14 02:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('programming', '0013_auto_20210902_1417'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionTypeBlockly',
            fields=[
                ('question_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='programming.question')),
            ],
            options={
                'verbose_name': 'Blockly Question',
                'verbose_name_plural': 'Blockly Questions',
            },
            bases=('programming.question',),
        ),
        migrations.CreateModel(
            name='QuestionTypeBlocklyTestCase',
            fields=[
                ('testcase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='programming.testcase')),
                ('test_input', models.CharField(blank=True, max_length=500)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_cases', to='programming.questiontypeblockly')),
            ],
            options={
                'verbose_name': 'Blockly Question Test Case',
            },
            bases=('programming.testcase',),
        ),
    ]
